name: Publish Presentation

on: 
  push:
    branches:
    - master
    paths:
    - '.github/workflows/publish_presentation.yml'
    - 'postprocessing/remove_out.py'
    - 'notebook/main-presentation.ipynb'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.6' 
    - name: install nbconvert
      run: pip install nbconvert==5.6.0
    - name: convert ipynb to slide.html
      run: |
        jupyter nbconvert notebook/main-presentation.ipynb  --TemplateExporter.exclude_input=True --to slides
        mv notebook/main-presentation.slides.html presentation/index.html
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: '' #optional defaults to master
